---
#install required packages and start them
- name: firewalld
  apt: name=firewalld state=present
- name: apache2
  apt: name=apache2 state=present
- name: apache2-start
  service: name=apache2 state=started
- name: mariadb
  apt: name=mariadb-server state=present
- name: php
  apt: name=php state=present
- name: php-mysql
  apt: name=php-mysql state=present
- name: mysql-start
  service: name=mysql state=started